services:
  - docker

env:
  matrix:
  - HTTPie_VERSION=2.0.0  PYTHON_IMAGE=python:3.8
  - HTTPie_VERSION=2.0.0  PYTHON_IMAGE=python:3.7
  - HTTPie_VERSION=2.0.0  PYTHON_IMAGE=python:3.6
  - HTTPie_VERSION=2.0.0  PYTHON_IMAGE=python:3.6

  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:3.8
  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:3.7
  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:3.6
  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:3.5
  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:3.4
  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:3.3
  - HTTPie_VERSION=1.0.3  PYTHON_IMAGE=python:2.7

  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:3.8
  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:3.7
  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:3.6
  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:3.5
  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:3.4
  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:3.3
  - HTTPie_VERSION=1.0.2  PYTHON_IMAGE=python:2.7

  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:3.8
  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:3.7
  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:3.6
  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:3.5
  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:3.4
  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:3.3
  - HTTPie_VERSION=1.0.1  PYTHON_IMAGE=python:2.7

  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:3.8
  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:3.7
  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:3.6
  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:3.5
  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:3.4
  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:3.3
  - HTTPie_VERSION=1.0.0  PYTHON_IMAGE=python:2.7
  # global:
  #   DOCKER_COMPOSE_VERSION: 1.25.4
before_install:
  # install the latest docker and docker-compose versions
  # - sudo apt-get remove docker docker-engine
  # - sudo curl -sSL https://get.docker.com/ | sh
  # - sudo rm /usr/local/bin/docker-compose
  # - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  # - chmod +x docker-compose
  # - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose --version
script:
  - docker-compose up
notifications:
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: jXjeY5Rh4nflRST0oAzwJbOTm23ddcViq2rXhQbbVD5Dz/G177tczBuwPSvrGmZlaipSillBWHMii+De/cPvDBCfYhLZRLk/pJJCbm9HXwzbX19vJtnmMzi0jCEYJk9ayaDr4s56Qn7GCMM89TRYhpEY8JpIPyaYhbsh38CL6czv9K0XcfrWGHQHoIdVvOVtrgeoYWPqmDWwKKKBVjS7X5uVZzEnk5Pg/+pC0lDGI1HDyE7tTJpI1ApHu3v/6iMuR9aDFepQXh7XjzhdopFSpSY0MPT1/6BrWH0pU8MqXjTwbL32XFDBswKYkDcCgP0OIU1AtYMNAVcSTS1kth4NF6BiqrNSWyM68Dmx3Gz09qEk3gylsOoxvoIKOUvJ+s6jo1q93tW+d3Vb9AlGE4Gi78W0uhoLOBbwaVnMUY5b+LW1HdTkDNpORJ3iTn1/CRPVA711fGv4e8P7EEBdcWWCufdU1cHMiQKTdY8NfiM2BXQVi+Y62h+61CxOMbVuY1esjRkIbEh2d+9Xrs5f1YMpBI+pH7VJlkYduPJqDvm6sU+JoAJEUc/WtU3BvIQtY0n+5jvWs9Rnbx7W5JPFMGrnxVMlhVWkiiUKDpARhSpHHuQ9zQuMcRMIrXk7/9ZiRbwsrQYOCw+pwz75RJCw8yT6LgsHWqBz7mZ6D2n2DVQtJl4=
