version: '3'

services:

  httpie:
    image: ${PYTHON_IMAGE:-python:3.8}
    working_dir: /opt/app
    command: bash -c "./run_qa.sh"
    environment:
      HTTPie_VERSION: ${HTTPie_VERSION:-2.0.0}
    volumes:
      - .:/opt/app
